* Changelog

All notable changes to this project will be documented in this file.

The format is based on Keep a Changelog, some adaptation apply: https://keepachangelog.com/en/1.1.0/.

This project also adheres to Semantic Versioning: https://semver.org/spec/v2.0.0.html.

** [0.3.0] 2026-09-20

*** Added

- In the default section, if the destination isn't defined, assume it to be the parent directory.

*** Changed

- Only the basename from the source is used to symlink, if a destination is provided.
- Ignore `file exist` error, if not verbose. This error happens commonly if `neostow` is ran twice, where the symlink fails due to existing symlink file.

** [0.2.0] 2026-09-02

The project has been rewritten in [[https://odin-lang.org/][Odin]].

*** Added

- ~.neostow~ file can be searched up in the directory tree.
- ~NEOSTOW_FILE~: replaces the default file, if none is provided
- ~neostow~ can be used as ~ln~ replacement.
- When ~neostow~ is used as ~ln~ replacement, and ~NEOSTOW_FILE~ is set, it can automatically add the symlink operation to the file.

*** Removed

- ~delete~ and ~edit~ commands were removed.
- All short flags were removed.
- ~--debug~, ~--file~ and ~--overwrite~ flags were removed.

** [0.1.0] 2026-10-19

Initial release
